local addonRoot = assert(arg and arg[1], "prepared addon root is required")
local addonLoader = assert(arg and arg[2], "addon loader path is required")
dofile(addonLoader)
local B, M, U = assert(BronzeLFG), assert(SignalFireMarketplace151), assert(SignalFireMarketplaceUI151)
BronzeLFG_DB.options.serverProfile = "Ascension"; BronzeLFG_DB.options.modulesByProfile = {Ascension={tradeskillMarketplace=true}}
assert(B:SFModulesApply() and B:ShowMarketplace(), "Marketplace did not open")
local function create(number)
  return assert(B:SFMarketplaceCreateListing({owner="Favorite Owner", listingType="Crafting Offer", profession="Alchemy", itemName="Favorite " .. number, priceMode="Tip", location="Dalaran", availability="Today", expiresAt=time()+7200}))
end
local active = create(1); assert(M:SetFavorite(active.id, true)); assert(U:SetTab("Favorites"), "Favorites did not open")
assert(U.favoritesView.total == 1 and U.favoritesRows[1].labels[5]:GetText() == "Active", "active favorite classification failed")
assert(U:SelectFavoriteRow(U.favoritesRows[1]) and U.favoriteDetailValues[12]:GetText() == "Active", "active detail failed")
assert(U:RemoveFavorite() and M:GetListing(active.id) and not M:IsFavorite(active.id), "unfavorite removed listing or failed")
assert(M:SetFavorite(active.id, true) and M:RemoveListing(active.id), "favorite setup removal failed")
assert(U:SetTab("Favorites") and U.favoritesRows[1].labels[5]:GetText() == "Unavailable", "unavailable classification failed")
assert(U:SelectFavoriteRow(U.favoritesRows[1]) and U.favoriteDetailValues[11]:GetText() == "This listing is no longer available.", "unavailable detail failed")
assert(U:RemoveFavorite() and not M:IsFavorite(active.id), "remove unavailable favorite failed")
BronzeLFG_DB.options.modulesByProfile.Ascension.tradeskillMarketplace=false; B:SFModulesApply()
assert(U:ActiveScriptCount() == 0 and not U.favoritesView, "Favorites disable cleanup failed")
print("marketplace favorites harness: PASS")
