const fs = require("fs");
const core = fs.readFileSync("SignalFire/SignalFireCore.lua", "utf8");
const chat = fs.readFileSync("SignalFire/SignalFireChat.lua", "utf8");
const ui = fs.readFileSync("SignalFire/SignalFireUI.lua", "utf8");
const listing = fs.readFileSync("SignalFire/SignalFireListing.lua", "utf8");
const harness = fs.readFileSync("tests/activity_discovery_pass_a_harness.lua", "utf8");
const loaderHarness = fs.readFileSync("tests/parser_regression_harness.lua", "utf8");
const workflow = fs.readFileSync(".github/workflows/release.yml", "utf8");
const need = (source, value, label) => { if (!source.includes(value)) throw new Error(`activity discovery source verification failed: ${label}`); };
need(core, 'basicDungeonDifficulties = {"Normal", "Heroic", "Mythic"}', "Ascension ordinary Dungeon profile list");
need(listing, 'if typeName == "Dungeon" then return {"Normal", "Heroic", "Mythic"} end', "final Ascension difficulty owner");
need(listing, 'state.difficulty ~= "Heroic" and state.difficulty ~= "Mythic"', "saved Mythic state preservation");
need(listing, 'difficulty == "Heroic" or difficulty == "Mythic"', "plain Mythic preview");
need(chat, "function B:SFDiscoverActivityPassA(text)", "authoritative discovery helper");
need(chat, "parsed.difficulty, parsed.keyLevel", "normalized discovery metadata");
need(chat, 'discovery.difficulty == "Mythic+" then parsed.type = "Key"', "Mythic+ precedence");
need(chat, 'parsed.type == "Raid"', "raid precedence");
need(chat, 'contains(input, " guild ")', "guild protection");
need(chat, 'result.difficulty = fast.difficulty', "core parser difficulty propagation");
need(chat, '"difficulty", "keyLevel", "key"', "reconciliation metadata preservation");
need(ui, "publicDifficultyFilter", "Public Groups difficulty state");
need(ui, '"All Difficulties", "Normal", "Heroic", "Mythic", "Mythic+"', "difficulty dropdown choices");
need(ui, "p6_difficulty_matches", "exact difficulty matcher");
need(ui, "record.difficulty", "difficulty search metadata");
if (ui.includes('record.difficulty == "Mythic+" and record.kind == "Key"')) throw new Error("activity discovery source verification failed: Mythic+ is incorrectly gated by type");
need(ui, 'panel, "TOPLEFT", 260, -92', "non-overlapping difficulty label placement");
need(ui, 'panel, "TOPLEFT", 318, -86', "non-overlapping difficulty dropdown placement");
need(workflow, "verify_activity_discovery_pass_a_sources.js", "workflow source verifier");
need(workflow, "activity_discovery_pass_a_harness.lua", "workflow Lua harness");
need(harness, "function JoinChannelByName", "joined BLFG channel simulation");
need(harness, "onlyListPacket", "production CreateListing packet capture");
need(harness, "RunDropdownInitializer", "actual difficulty dropdown callback coverage");
need(harness, "filtered-out selected Public Group was retained", "selected row clearing coverage");
need(harness, "for _ = 1, 20 do", "geometry/reuse lifecycle coverage");
need(harness, "LIST packet expanded past p[26]", "current LIST packet compatibility coverage");
need(loaderHarness, "function objectMethods:SetPoint", "stored mock geometry");
need(loaderHarness, "function UIDropDownMenu_Initialize", "stored dropdown initializer mock");
if (/p\[27\]|p\[28\]/.test(chat + core + ui)) throw new Error("activity discovery source verification failed: packet expansion");
console.log("activity discovery pass A source verification: PASS");
