const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const read = file => fs.readFileSync(path.join(root, file), "utf8");
const need = (s, value, label) => { if (!s.includes(value)) throw new Error(`Marketplace 2A verification failed: ${label}`); };
const forbid = (s, value, label) => { if (s.includes(value)) throw new Error(`Marketplace 2A verification failed: forbidden ${label}`); };
const toc = read("SignalFire/SignalFire.toc"), network = read("SignalFire/SignalFireNetwork.lua"), core = read("SignalFire/SignalFireMarketplace.lua"), market = read("SignalFire/SignalFireMarketplaceNetwork.lua"), ui = read("SignalFire/SignalFireMarketplaceUI.lua");
if (toc.indexOf("SignalFireMarketplace.lua") > toc.indexOf("SignalFireMarketplaceNetwork.lua") || toc.indexOf("SignalFireMarketplaceNetwork.lua") > toc.indexOf("SignalFireMarketplaceUI.lua")) throw new Error("Marketplace 2A verification failed: TOC ordering");
need(network, "function BLFG:RegisterNetworkPacketHandler(typeName, owner, callback)", "extension registration");
need(network, "KnownNetworkPacketTypes2A = BLFG.KnownNetworkPacketTypes2A or {MKT2=true}", "bounded extension type");
need(network, "#final > 255", "final packet bound");
need(network, "pcall(entry.callback, entry.owner, p, author or \"\", msg)", "protected extension dispatch");
need(market, "protocolVersion, N.maximumPacket, N.maximumChunks, N.maximumPayload = 1, 255, 8, 1024", "version and packet bounds");
need(market, "N.maximumPending, N.pendingTTL, N.maximumDedup, N.dedupTTL = 32, 30, 256, 120", "pending and dedup bounds");
need(market, "N.maximumOutgoing, N.maximumRemote, N.sendSpacing = 64, 200", "outgoing and remote bounds");
need(market, "M:OwnerKey(row.owner)~=M:OwnerKey(author)", "sender ownership validation");
need(market, "runtime.remoteById", "session remote runtime");
need(market, "function N:Disable()", "network teardown");
need(core, "remoteById={}, remoteOrder={}, remoteSourceById={}, remoteCount=0", "remote runtime ownership");
need(core, "network:QueueUpsert(row)", "local upsert broadcast");
need(core, "network:QueueRemove(row)", "local removal broadcast");
need(ui, "runtime.remoteOrder", "Browse merges remote records");
forbid(market, "SendChatMessage(", "direct Marketplace sender");
forbid(market, "OnUpdate", "Marketplace network OnUpdate");
forbid(market, "NewTicker", "Marketplace network ticker");
forbid(market, "ChatFrame_AddMessageEventFilter", "ChatFrame filter");
console.log("marketplace phase2a network source verification: PASS");
