const fs = require("fs");
const core = fs.readFileSync("SignalFire/SignalFireCore.lua", "utf8");
const chat = fs.readFileSync("SignalFire/SignalFireChat.lua", "utf8");
const ui = fs.readFileSync("SignalFire/SignalFireUI.lua", "utf8");
const workflow = fs.readFileSync(".github/workflows/release.yml", "utf8");
const need = (source, value, label) => { if (!source.includes(value)) throw new Error(`activity discovery source verification failed: ${label}`); };
need(core, 'basicDungeonDifficulties = {"Normal", "Heroic", "Mythic", "Mythic+"}', "Ascension plain Mythic creation list");
need(chat, "function B:SFDiscoverActivityPassA(text)", "authoritative discovery helper");
need(chat, "parsed.difficulty, parsed.keyLevel", "normalized discovery metadata");
need(chat, 'discovery.difficulty == "Mythic+" then parsed.type = "Key"', "Mythic+ precedence");
need(chat, 'parsed.type == "Raid"', "raid precedence");
need(chat, 'contains(input, " guild ")', "guild protection");
need(ui, "publicDifficultyFilter", "Public Groups difficulty state");
need(ui, '"All Difficulties", "Normal", "Heroic", "Mythic", "Mythic+"', "difficulty dropdown choices");
need(ui, "p6_difficulty_matches", "exact difficulty matcher");
need(ui, "record.difficulty", "difficulty search metadata");
need(workflow, "verify_activity_discovery_pass_a_sources.js", "workflow source verifier");
need(workflow, "activity_discovery_pass_a_harness.lua", "workflow Lua harness");
if (/p\[27\]|p\[28\]/.test(chat + core + ui)) throw new Error("activity discovery source verification failed: packet expansion");
console.log("activity discovery pass A source verification: PASS");
